# Swift Lint Rule Customize 
disabled_rules:
  - unused_optional_binding
  - identifier_name
  - force_cast
opt_in_rules:

included:
excluded:
  - Carthage
  - Pods
  
# rules
line_length:
  warning: 200
  error: 300
