# Swift Lint Rule Customize 
disabled_rules:
  - unused_optional_binding
opt_in_rules:

included:
excluded:
  - Carthage
  - Pods
  
# rules
identifier_name:
  min_length: # only min_length
    warning: 2
    error: 1

line_length:
  warning: 200
  error: 300
